In [ ]:
"""
Dataset and DataLoader
- epoch = 1 forward and backward pass of ALL training samples
- batch_size = number of training samples in one forward & backward pass

batch gradient descent is not used generally bcz it is
- memory inefficient
- computation expensive
- not good convergence

 so we use mini batch gradient descent

"""

In [ ]:
"""
Dataset Dataloaders are core abstractors in pytorch that decouple  how you define data from how you efficiently iterate over it in training loops
- our data is inside the memory, now we need to load this data from memory
- this loading work is done by dataset class, so dataset class knows where our data is from memory class

Dataloader -> does work of making batches
- har batch me kitne rows hoge
- these batches are sent to training loop

- data load krne ka kaam -> dataset
- batches load krne ka kaam -> dataloader
"""
"""

In [ ]:
"""
dataset -> abstarct class
- we need to mmake 3 methods in this class
-> __init__ : data load kese and kaha se hoga
-> __len__ : total kitne number of rows hai
-> __getitem__(index) :  we give index value and this gives that row
"""

In [ ]:
"""
Dataloader uses 'sampler' to shuffle indices
- then makes batches and sens to getitem method of dataset class

"""

In [1]:
from sklearn.datasets import make_classification
import torch

In [3]:
x, y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [4]:
x

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [5]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [6]:
# convert to tensor
x = torch.tensor(x, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [7]:
x

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [8]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [9]:
from torch.utils.data import Dataset, DataLoader

In [13]:
class customDataset(Dataset):
    def __init__(self, features, labels):

        self.features = features
        self.labels = labels


    def __len__(self):
        return self.features.shape[0] #return number of rows

    def __getitem__(self, index):
        return self.features[index], self.labels[index]


In [15]:
dataset = customDataset(features=x, labels=y)

In [16]:
len(dataset)

10

In [17]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [18]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [19]:
for batch_features, batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("---"*10)

tensor([[-1.1402, -0.8388],
        [-1.9629, -0.9923]])
tensor([0, 0])
------------------------------
tensor([[ 1.7273, -1.1858],
        [-0.5872, -1.9717]])
tensor([1, 0])
------------------------------
tensor([[ 1.0683, -0.9701],
        [ 1.7774,  1.5116]])
tensor([1, 1])
------------------------------
tensor([[-0.7206, -0.9606],
        [-2.8954,  1.9769]])
tensor([0, 0])
------------------------------
tensor([[-0.9382, -0.5430],
        [ 1.8997,  0.8344]])
tensor([1, 1])
------------------------------


In [ ]:
# in dataset class, in getitem method, we can apply any transformation before returning to that row

In [20]:
type(dataloadergithub galaxy brain)

torch.utils.data.dataloader.DataLoader

In [ ]:
# worker -> dataloader, for ||
