In [ ]:
"""
nn module -> functionality to create neurons
- has activation functions, loss function
- torch.optim -> built in optimizers
"""

In [ ]:
"""
torch.nn
- core library providing array of classes and function to develop nn
- offers pre-built layers, loss func, activation function

Key components
- layers : nn.Linear, nn.Conv2d, nn.LSTM
nn.Module

- activation func: nn.ReLU, nn.Sigmoid, nn.Tanh
- loss; nn.MSELoss, nn.CrossEntropyLoss
- optimizers: torch.optim.SGD, torch.optim.Adam
-container module: nn.Sequential, nn.ModuleList, nn.ModuleDict
nn.Dropout, nn.BatchNorm2d
"""

In [1]:
# create model class
import torch
import torch.nn as nn

In [3]:
# nn
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        # we will create our layer here
        self.linear = nn.Linear(num_features, 1) # input, output
        self.activation = nn.Sigmoid()

    def forward(self, features):
        # output calculation
        out = self.linear(features)
        out = self.activation(out) #y_pred
        return out

In [4]:
# dataset
features = torch.rand(10,5)

In [5]:
features

tensor([[0.6648, 0.4719, 0.0075, 0.0962, 0.6709],
        [0.9215, 0.1542, 0.5570, 0.9894, 0.2982],
        [0.4337, 0.3392, 0.9579, 0.6851, 0.5969],
        [0.5838, 0.9589, 0.6350, 0.9103, 0.1394],
        [0.1888, 0.3527, 0.0372, 0.8755, 0.2481],
        [0.1115, 0.4244, 0.9052, 0.0958, 0.2701],
        [0.9227, 0.6845, 0.3468, 0.0684, 0.2232],
        [0.0463, 0.7179, 0.7933, 0.9076, 0.2014],
        [0.5669, 0.4090, 0.6368, 0.8967, 0.1475],
        [0.7795, 0.5243, 0.7770, 0.3545, 0.9519]])

In [6]:
model = Model(features.shape[1])


In [7]:
model(features)

tensor([[0.4353],
        [0.5348],
        [0.4329],
        [0.4497],
        [0.5302],
        [0.3988],
        [0.4281],
        [0.4467],
        [0.5010],
        [0.3823]], grad_fn=<SigmoidBackward0>)

In [ ]:
# __call__ is getting overriden here to  trigger forward method

In [10]:
model.linear.weight

Parameter containing:
tensor([[ 0.0812, -0.3910, -0.2713,  0.3271, -0.2991]], requires_grad=True)

In [11]:
model.linear.bias

Parameter containing:
tensor([0.0416], requires_grad=True)

In [12]:
!pip install torchinfo

In [13]:
from torchinfo import summary

In [14]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [16]:
## creating nn with hidden layer
class NNTwo(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.layer1 = nn.Linear(num_features,3)
        self.layer2 = nn.Linear(3,1)
        self.activation1 = nn.ReLU()
        self.activation2 = nn.Sigmoid()


    def forward(self, features):
        out = self.layer1(features)
        out = self.activation1(out)
        out = self.layer2(out)
        out = self.activation2(out)
        return out

In [17]:
features = torch.rand(10,5)

In [18]:
features

tensor([[0.9293, 0.3105, 0.0960, 0.8336, 0.2753],
        [0.7803, 0.0189, 0.6353, 0.2942, 0.9442],
        [0.5693, 0.5506, 0.6901, 0.2318, 0.8165],
        [0.0450, 0.9375, 0.9622, 0.2028, 0.4521],
        [0.7163, 0.4790, 0.2567, 0.1397, 0.9670],
        [0.3037, 0.6203, 0.4189, 0.5839, 0.4660],
        [0.7140, 0.2467, 0.6790, 0.2601, 0.2983],
        [0.5416, 0.4283, 0.8954, 0.7925, 0.9865],
        [0.6043, 0.9550, 0.6398, 0.5620, 0.3833],
        [0.6043, 0.7730, 0.2243, 0.2789, 0.3735]])

In [19]:
model = NNTwo(features.shape[1])

In [20]:
model(features)

tensor([[0.4314],
        [0.4581],
        [0.4565],
        [0.4559],
        [0.4538],
        [0.4428],
        [0.4448],
        [0.4596],
        [0.4437],
        [0.4394]], grad_fn=<SigmoidBackward0>)

In [21]:
summary(model, (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
NNTwo                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [23]:
# simplify forward function - we use sequential container
class Test(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
    )

    def forward(self, features):
        return self.network(features)

In [ ]:
"""
torch.optim - provides variety of optm algo to update parameters of model during training
- includes common optimizers like SGDm ,Adam, RMSprop
-
"""