In [ ]:
# flow
#  tensor -> how to manipulate them

In [ ]:
"""
Tensor -> higher dim arrays designed for mathematical and computational efficiency
- dim -> kitne direction me tensor span kr raha hai
- 0 dim - scalar
- 1 dim - vector
- 2 dim - matrix


2 dim -> eg., grey scale image
3 dim -> eg., rgb image/colored image
4 dim -> eg., batches of rgb images (batch_size x width x height x channels)
5 dim -> video data, video has frames and each frame is image
"""



In [ ]:
"""
Why tensor?
- mathematical operations are aasan using tensor
- represent real world data as tensor
- we can run tensors on GPU and parallise them


Where are tensors used in DL?
- Data storage
- weights and biases
- matrix operations
- training process - forward pass
"""

In [2]:
import torch

In [3]:
print(torch.__version__)

2.10.0+cu128


In [6]:
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("Sorry buddy!")

GPU: Tesla T4


In [5]:
torch.cuda.get_device_name()

'Tesla T4'

## Creating Tensor


In [8]:
# using empty
a = torch.empty(2,3)
# this allocates memory but it doesn't assign any value to the space
# so below result is value which is already in memory assigned

In [9]:
# type
type(a)

torch.Tensor

In [10]:
# zeros
torch.zeros(2,3)
# all values will be initialized by 0s

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
# ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
# 'rand' function
torch.rand(2,3)
# each value will be between 0 and 1 and random

tensor([[0.1111, 0.6980, 0.1957],
        [0.9671, 0.9673, 0.5084]])

In [13]:
# 'seed' function
# 'rand' function gives different value every time
# so we set output to be same i/e why we define seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
# tensor
# to create custom tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
# other ways
# arange
print(torch.arange(0,10)) #start_val,range,step

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [18]:
# using linespace
torch.linspace(0,10,steps=5) # linearly spaced --> range and 5 evenly spaced values chahiye

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [20]:
# eye -> identity matrx
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [22]:
# full -> give shape and how each item should be
torch.full((3,4),2)
# matrix of size 3x4 and each item should be 2

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])

## Tensor Shape

In [24]:
x = torch.tensor([[2,3,4],[4,6,2]])
x.shape

torch.Size([2, 3])

In [26]:
# we have one shape and wish to create same shape tensor
# empty_like
torch.empty_like(x)
# values alag but same shape

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6067246093688646966, 3688512095000343089, 6500442731540133678]])

In [27]:
# zeros_like(x)
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [28]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [29]:
# rand_like
torch.rand_like(x)
# this won't work bcz x has int items but rand generates float
# so, let's learn about data types

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

## Tensor Data Types

In [30]:
# find data type
x.dtype # dtype is attribute

torch.int64

In [31]:
# assign data type
torch.ones((2,3),dtype=torch.float)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [32]:
torch.tensor((3,2), dtype=torch.int)

tensor([3, 2], dtype=torch.int32)

In [33]:
# change data type
x.to(torch.float32)

tensor([[2., 3., 4.],
        [4., 6., 2.]])

In [35]:
torch.rand_like(x, dtype=torch.float)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Mathematical operations on Tensor

In [38]:
x = torch.rand(2,2)
x

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [39]:
# scalar operations
x = x + 2
x

tensor([[2.9969, 2.7565],
        [2.2239, 2.3023]])

In [ ]:
# same way we can do sub, mul, div, mod, pow

In [40]:
# element wise operation
a = torch.rand(2,3)
b = torch.rand(2,3)


In [42]:
c = a + b

In [43]:
c.round()

tensor([[1., 1., 1.],
        [2., 1., 1.]])

In [44]:
c.ceil() # upar vala

tensor([[1., 2., 1.],
        [2., 1., 2.]])

In [45]:
c.floor()

tensor([[0., 1., 0.],
        [1., 0., 1.]])

In [47]:
# clamp -> ek range me rakh sakte saare numbers ko
torch.clamp(c, 2,3)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

## reduction operation

In [49]:
e = torch.randint(size=(2,3),low= 0,high = 10)

In [50]:
e

tensor([[0, 9, 5],
        [7, 3, 9]])

In [51]:
# reduce to a number
e.sum()

tensor(33)

In [52]:
torch.sum(e, dim=0) # col

tensor([ 7, 12, 14])

In [53]:
torch.sum(e, dim=1) # row

tensor([14, 19])

In [55]:
e.mean(dtype=torch.float)

tensor(5.5000)

In [56]:
torch.median(e)

tensor(5)

In [ ]:
# max, min, prodcut(prod), std, var

In [57]:
torch.argmax(e) # bade item ka position

tensor(1)

In [58]:
torch.argmin(e)

tensor(0)

In [59]:
e

tensor([[0, 9, 5],
        [7, 3, 9]])

In [ ]:
# matrix multiplication b/w a and b
torch.matmul(a,b)

In [60]:
# transpose
torch.transpose(e,0,1) # pehle kis dim ko swap krna hai -> 0 ko 1 se swap

tensor([[0, 7],
        [9, 3],
        [5, 9]])

In [61]:
# determinant
torch.det(e)

RuntimeError: linalg.det: A must be batches of square matrices, but they are 2 by 3 matrices

In [62]:
f = torch.rand(2,2)

In [63]:
torch.det(f)

tensor(-0.4537)

In [64]:
# inverse
torch.inverse(f)

tensor([[-0.0791,  1.9619],
        [ 1.1378, -0.3590]])

In [2]:
import torch

In [4]:
# let's see difference of time between cpu and gpu
import time

size = 10000

mtrx_1 = torch.randn(size, size)
mtrx_2 = torch.randn(size, size)

start_time = time.time()
result_cpu = torch.matmul(mtrx_1, mtrx_2)
cpu_end_time = time.time() - start_time

print("CPU TIME:", cpu_end_time)

start_time = time.time()
result_gpu = torch.matmul(mtrx_1.to('cuda'), mtrx_2.to('cuda'))
torch.cuda.synchronize()
gpu_end_time = time.time() - start_time

print("GPU TIME:", gpu_end_time)

CPU TIME: 24.924022912979126
GPU TIME: 1.2571792602539062
